### ISSUE TITLE
sync.exe for my Win 10 pc

### ISSUE THREAD

**Issue by fmgburner25** [TheRedSpy15/blazedcloud-sync#1]
How do I download a sync.exe for my Win 10 pc from your source https://github.com/TheRedSpy15/blazedcloud? thank you!

**Comment by TheRedSpy15** [comment]
You download and extract it from the zip located at https://github.com/TheRedSpy15/blazedcloud-sync/releases/latest

**Comment by fmgburner25** [comment]
Hi what means the info Backend URL: https://pb.blazedcloud.com/ into the log file?

[db.json](https://github.com/TheRedSpy15/blazedcloud-sync/files/14586951/db.json)
[log.txt](https://github.com/TheRedSpy15/blazedcloud-sync/files/14586952/log.txt)

I can login via blazedcloud-sync-0.1.0.exe but then it will close - why?

**Comment by TheRedSpy15** [comment]
Your link to the log.txt file is invalid, but the `Backend URL: https://pb.blazedcloud.com/` can be ignored, it's just the url the application is using to communicate with the service

But it does look like the error you're experiencing based on the video is related to a connection timeout. Not sure to where without seeing the log file

**Comment by fmgburner25** [comment]
I have update the log file in the last comment. I use your softwar into a goverment work station and there will many side blocked but there I want to sync some file to my phone. I found till now no current solution to do this. I will try it onto my personal pc. bye

**Comment by fmgburner25** [comment]
Hi I tried it now at my personal pc without any network or firwall problems, but the sync progress are also not working. Please help me! Thank you a lot!
![2024 03 15 10h53min52sec](https://github.com/TheRedSpy15/blazedcloud-sync/assets/38662262/4ee841a5-88c4-4803-968f-5ba2a4393501)

**Comment by fmgburner25** [comment]
Hi I tried it now at my personal pc without any network or firwall problems, but the sync progress are also not working. Please help me! Thank you a lot!

![2024 03 15 11h24min52sec](https://github.com/TheRedSpy15/blazedcloud-sync/assets/38662262/edc4040e-0c8b-4182-9d36-b8d7dfc27522)

**Comment by TheRedSpy15** [comment]
@fmgburner25 can you confirm the `Download.txt` is not in the download directory? The provided screenshot shows the file downloaded successfully
